import type { Metadata } from 'next';
import { Inter } from "next/font/google";

const inter = Inter({
  weight: ["400", "500", "600"],
  variable: "--font-latin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
