import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Home: React.FC = () => {
  return <main>hello</main>;
};

export default Home;
